variables_to_extract = {
    # Tables type 1 variables:
    "Patient Information": [
        "Last",
        "First",
        "Middle",
        "Name Suffix",
        "Sex",
        "Gender",
        "DOB",
        "Age",
        "Weight-lbs",
        "Weight-kg",
        "Height-ft",
        "Height- cm",
        "Pedi Color",
        "SSN",
        "Advance Directives",
        "Resident Status",
        "Patient Resides in Service Area",
        "Temporary Residence Type",
        "Address",
        "Address 2",
        "City",
        "State",
        "Zip",
        "Country",
        "Tel",
        "Physician",
        "Phys. Tel",
        "Ethnicity",
        "Race",
        # Clinical Impression
        "Primary Impression",
        "Secondary Impression",
        "Protocols Used",
        "Local Protocol Provided",
        "Care Level",
        "Anatomic Position",
        "Onset Time",
        "Last Known Well",
        "Chief Complaint",
        "Duration",
        "Duration Units",
        "Secondary Complaint",
        "Secondary Duration",
        "Secondary Duration Units",
        "Patient Level of Distress",
        "Signs Symptoms",
        "Injury",
        "Additional Injury",
        "Mechanism of Injury",
        "Medical Trauma",
        "Barriers of Care",
        "Alcohol Drugs",
        "Pregnancy",
        "Initial Patient Acuity",
        "Final Patient Acuity",
        "Patient Activity",
    ],
    "Medications/Allergies/History/Immunizations": [
        "Medications",
        "Allergies",
        "History",
        "Immunizations",
    ],
    "Specialty Patient - CPR": [
        "Cardiac Arrest",
        "Cardiac Arrest Etiology",
        "Estimated Time of Arrest",
        "Est Time Collapse to 911",
        "Est Time Collapse to CPR",
        "Arrest Witnessed By",
        "CPR Initiated By",
        "Time 1st CPR",
        "CPR Feedback",
        "ITD Used",
        "Applied AED",
        "Applied By",
        "Defibrillated",
        "CPR Type",
        "Prearrival CPR Instructions",
        "First Defibrillated By",
        "Time of First Defib",
        "Initial ECG Rhythm",
        "Rhythm at Destination",
        "Hypothermia",
        "End of Event",
        "ROSC",
        "ROSC Time",
        "ROSC Occurred",
        "Resuscitation Discontinued",
        "Discontinued Reason",
        "Resuscitation",
        "Expired",
        "Time",
        "Date",
        "Physician",
    ],
    "Incident Details": [
        "Location Type",
        "Location",
        "Address",
        "Address 2",
        "Mile Marker",
        "City",
        "County",
        "State",
        "Zip",
        "Country",
        "Medic Unit",
        "Medic Vehicle",
        "Run Type",
        "Response Mode",
        "Response Mode Descriptors",
        "Shift",
        "Zone",
        "Level of Service",
        "EMD Complaint",
        "EMD Card Number",
        "Dispatch Priority",
        # Destination Details
        "Disposition",
        "Unit Disposition",
        "Patient Evaluation and/or Care Disposition",
        "Crew Disposition",
        "Transport Disposition",
        "Transport Mode",
        "Reason for Refusal or Release",
        "Transport Mode Descriptors",
        "Transport Due To",
        "Transported To",
        "Requested By",
        "Transferred To",
        "Transferred Unit",
        "Destination",
        "Department",
        "Address",
        "Address 2",
        "City",
        "County",
        "State",
        "Zip",
        "Country",
        "Zone",
        "Condition at Destination",
        "State Wristband",
        "Destination Record",
        "Trauma Registry ID",
        "STEMI Registry ID",
        "Stroke Registry ID",
        # Incident Times
        "PSAP Call",
        "Dispatch Notified",
        "Call Received",
        "Dispatched",
        "En Route",
        "Staged",
        "Resp on Scene",
        "On Scene",
        "At Patient",
        "Care Transferred",
        "Depart Scene",
        "At Destination",
        "Pt. Transferred",
        "Call Closed",
        "In District",
        "At Landing Area",
    ],
    "Insurance Details": [
        "Insured Name",
        "Relationship",
        "Insured SSN",
        "Insured DOB",
        "Address1",
        "Address2",
        "Address3",
        "City",
        "State",
        "Zip",
        "Country",
        "Primary Payer",
        "Medicare",
        "Medicaid",
        "Primary Insurance",
        "Primary Insurance Policy #",
        "Primary Insurance Group Name",
        "Primary Insurance Group #",
        "Secondary Ins",
        "Secondary Insurance Policy #",
        "Secondary Insurance Group Name",
        "Secondary Insurance Group #",
        "Dispatch Nature",
        "Response Urgency",
        "Job Related Injury",
        "Employer",
        "Contact",
        "Phone",
        "Mileage to Closest Hospital",
    ],
    "Mileage": [
        "Scene",
        "Destination",
        "Loaded Miles",
        "Start",
        "End",
        "Total Miles",
        # Delays
        "Dispatch Delays",
        "Response Delays",
        "Scene Delays",
        "Transport Delays",
        "Turn Around Delays",
        # Additional
        "Additional Agencies",
    ],
    "Specialty Patient - Motor Vehicle Collision": [
        "Patient Injured",
        "Vehicle Type",
        "Position In Vehicle",
        "Seat Row",
        "Number Of Vehicles",
        "Weather",
        "Extrication Required",
        "Estimated Speed",
        "Exterior Damage",
        "Law Enforcement Case #",
        "Collision Indicators",
        "Damage Location",
        "Airbag Deployment",
        "Safety Devices",
        "Extrication Comments",
        "Extrication Time",
    ],
    "Specialty Patient - Trauma Criteria": [
        "Anatomic",
        "Physiologic",
        "Mechanical",
        "Other Conditions",
        "Trauma Activation",
        "Time",
        "Date",
        "Trauma level",
        "Reason Not Activated",
    ],
    "Specialty Patient - CDC 2011 Trauma Criteria": [
        "Vital Signs",
        "Anatomy of Injury",
        "Mechanism of Injury",
        "Special Considerations",
        "Trauma Activation",
        "Time",
        "Date",
        "level",
        "Reason Not Activated",
    ],
    "Transfer Details": [
        "PAN",
        "Prior Authorization Code Payer",
        "PCS",
        "Interfacility Transfer or Medical Transport Reason",
        "ABN",
        "CMS Service Level",
        "ICD-9 Code",
        "Transport Assessment",
        "Specialty Care Transport Provider",
        "Transfer Reason",
        "Justification for Transfer",
        "Other/Services",
        "Medical Necessity",
        "Sending Physician",
        "Sending Record #",
        "Receiving Physician",
        "Condition Code",
        "Condition Code Modifiers",
    ],
    "Patient Transport Details": [
        "How was Patient Moved To Stretcher",
        "How was Patient Moved From Ambulance",
        "Condition of Patient at Destination",
        "How was Patient Moved To Ambulance",
        "Patient Position During Transport",
    ],
    "Patient Refusal": [
        "Signed By",
    ],
    # Tables type 2 variables:
    "Vital Signs": [
        "AVPU",
        "Side",
        "POS",
        "BP",
        "Pulse",
        "RR",
        "SPO2",
        "ETCO2",
        "CO",
        "BG",
        "Temp",
        "Pain",
    ],
    "Vitals Calculations": [
        "GCS Qualifiers",
        "RASS",
        "BARS",
        "RTS",
        "PTS",
        "MAP",
        "Shock Index",
    ],
    "Flow Chart": [
        "Time",
        "Treatment",
        "Description",
    ],
    "ECG": [
        "Time",
        "Type",
        "Rhythm",
        "Notes",
    ],
    "Specialty Patient - Advanced Airway": [
        "Airway",
        "Indications",
        "Monitoring Devices",
        "Rescue Devices",
        "Reasons Failed Intubation",
    ],
    "Specialty Patient - Spinal Immobilization": [
        "Immobilization Recommended?",
        "Altered Mental Status",
        "Evidence of Alcohol/Drug Impairment",
        "Distracting Injury",
        "Neurologic Deficit",
        "Spinal Pain/Tenderness",
    ],
    # Tables type 4 variables:
    "Narrative": [
        "Narrative",
    ],
    # Tables type 5 variables:
    "Consumables": [
        "Description",
        "Qty",
    ],
}

